module.exports = {
    vards: [{
        name: "1337",
        image: 1
    }, {
        name: "Accesoar",
        image: 1
    }, {
        name: "AfterEight",
        image: 1
    }, {
        name: "Attityd",
        image: 1
    }, {
        name: "Berlin",
        image: 1
    }, {
        name: "Bolt",
        image: 1
    }, {
        name: "Bonn",
        image: 1
    }, {
        name: "Broderi",
        image: 1
    }, {
        name: "Dans",
        image: 1
    }, {
        name: "Dessert",
        image: 1
    }, {
        name: "Dryg",
        image: 1
    }, {
        name: "Fab",
        image: 1
    }, {
        name: "Fin",
        image: 1
    }, {
        name: "Fist",
        image: 1
    }, {
        name: "Fnul",
        image: 1
    }, {
        name: "F\u00f6r\u00e4ld",
        image: 1
    }, {
        name: "Fr\u00e4ls",
        image: 1
    }, {
        name: "Fuck",
        image: 1
    }, {
        name: "Full",
        image: 1
    }, {
        name: "Gr\u00e5t",
        image: 1
    }, {
        name: "Grill",
        image: 1
    }, {
        name: "Gubb",
        image: 1
    }, {
        name: "Hajk",
        image: 1
    }, {
        name: "B\u00e4ttreh\u00e4lft",
        image: 1
    }, {
        name: "Halvfem",
        image: 1
    }, {
        name: "Hatt",
        image: 1
    }, {
        name: "Hj\u00e4lm",
        image: 1
    }, {
        name: "H\u00f6g",
        image: 1
    }, {
        name: "Holly",
        image: 1
    }, {
        name: "Hood",
        image: 1
    }, {
        name: "Hulk",
        image: 1
    }, {
        name: "Invalid",
        image: 1
    }, {
        name: "Invit",
        image: 1
    }, {
        name: "J\u00e4nk",
        image: 1
    }, {
        name: "Jobb",
        image: 1
    }, {
        name: "Kalufs",
        image: 1
    }, {
        name: "Klubb",
        image: 1
    }, {
        name: "Komplex",
        image: 1
    }, {
        name: "K\u00f6pochs\u00e4lj",
        image: 1
    }, {
        name: "Koreograf",
        image: 1
    }, {
        name: "Korv",
        image: 1
    }, {
        name: "Kromosom",
        image: 1
    }, {
        name: "Meth",
        image: 1
    }, {
        name: "N\u00e4r",
        image: 1
    }, {
        name: "Njut",
        image: 1
    }, {
        name: "N\u00f6rd",
        image: 1
    }, {
        name: "Ornitolog",
        image: 1
    }, {
        name: "P\u00e4rlplatt",
        image: 1
    }, {
        name: "Partaj",
        image: 1
    }, {
        name: "Pepsodent",
        image: 1
    }, {
        name: "Pung",
        image: 1
    }, {
        name: "Rekvisit",
        image: 1
    }, {
        name: "Rock",
        image: 1
    }, {
        name: "Romans",
        image: 1
    }, {
        name: "Rump",
        image: 1
    }, {
        name: "Ryss",
        image: 1
    }, {
        name: "Self",
        image: 1
    }, {
        name: "Sexonthebeach",
        image: 1
    }, {
        name: "Sj\u00e4lv",
        image: 1
    }, {
        name: "Slem",
        image: 1
    }, {
        name: "Slips",
        image: 1
    }, {
        name: "Slir",
        image: 1
    }, {
        name: "Smajl",
        image: 1
    }, {
        name: "Snusk",
        image: 1
    }, {
        name: "Snygg",
        image: 1
    }, {
        name: "Solochv\u00e5r",
        image: 1
    }, {
        name: "Spliff",
        image: 1
    }, {
        name: "Stark",
        image: 1
    }, {
        name: "Student",
        image: 1
    }, {
        name: "Sudd",
        image: 1
    }, {
        name: "Surprise",
        image: 1
    }, {
        name: "T\u00f6rl",
        image: 1
    }, {
        name: "Tysk",
        image: 1
    }, {
        name: "Vin",
        image: 1
    }, {
        name: "Wizz",
        image: 1
    }, {
        name: "WTF",
        image: 1
    }, {
        name: "Appro",
        image: 1
    }, {
        name: "Tr\u00f6tt",
        image: 1
    }, {
        name: "Sk\u00e5l",
        image: 1
    }, {
        name: "Socker",
        image: 0
    }, {
        name: "Skryt",
        image: 0
    }, {
        name: "T\u00e5rt",
        image: 0
    }, {
        name: "Phone",
        image: 0
    }, {
        name: "Kul",
        image: 0
    }, {
        name: "E-",
        image: 0
    }, {
        name: "Bror",
        image: 0
    }, {
        name: "Soss",
        image: 0
    }, {
        name: "\u00c4lsk",
        image: 0
    }, {
        name: "Dr\u00e4gg",
        image: 0
    }, {
        name: "Shot",
        image: 0
    }, {
        name: "Fitt",
        image: 0
    }, {
        name: "Natt",
        image: 0
    }, {
        name: "Klot",
        image: 0
    }, {
        name: "Tack",
        image: 0
    }, {
        name: "",
        image: 0
    }, {
        name: "slump",
        image: 0
    }, {
        name: "Kalas",
        image: 0
    }, {
        name: "Badass",
        image: 0
    }, {
        name: "Stropp",
        image: 0
    }, {
        name: "Blom",
        image: 0
    }, {
        name: "Hus",
        image: 0
    }, {
        name: "Skogs",
        image: 0
    }, {
        name: "Snopp",
        image: 0
    }, {
        name: "brall",
        image: 0
    }, {
        name: "Fragg",
        image: 0
    }],
    vards_img: ['1337', 'accesoar', 'aftereight', 'appro',
        'attityd', 'battrehalft', 'berlin', 'bolt',
        'bonn', 'broderi', 'dans', 'dessert', 'dryg',
        'fab', 'fin', 'fist', 'fnul', 'forald', 'frals',
        'fuck', 'full', 'grat', 'grill', 'gubb', 'hajk',
        'halvfem', 'hatt', 'hjalm', 'hog', 'holly', 'hood',
        'hulk', 'invalid', 'invit', 'jank', 'jobb', 'kalufs',
        'klubb', 'komplex', 'kopochsalj', 'koreograf', 'korv',
        'kromosom', 'meth', 'nar', 'njut', 'nord', 'ornitolog',
        'parlplatt', 'partaj', 'pepsodent', 'pung', 'rekvisit',
        'rock', 'romans', 'rump', 'ryss', 'self', 'sexonthebeach',
        'sjalv', 'skal', 'slem', 'slips', 'slir', 'smajl', 'snusk',
        'snygg', 'solochvar', 'spliff', 'stark', 'student', 'sudd',
        'surprise', 'torl', 'trott', 'tysk', 'vin', 'wizz', 'wtf']
};